### ISSUE TITLE
Adopting logging into next daq release (v2.3.0 or v2.4.0)

### ISSUE THREAD

**Issue by ron003** [DUNE-DAQ/logging#1]
several packages will need to be changed.

**Comment by dingp** [comment]
`v1.0.0` has been built and published to cvmfs. Details in DUNE-DAQ/daq-release#46.

**Comment by ron003** [comment]
I have at least partial integration into several of the packages needed to run the minidaq demonstration:

- appfwk networkqueue dfmodules readout trigemu ipm

I have a PR in for dfmodules and am working on PRs for the others. Some of the packages I do not have access to and cannot push a branch.

**Comment by ron003** [comment]
logging is in dune daq sw release v2.2.0

**Comment by ron003** [comment]
logging is in dune daq sw release 2.2.0
