### ISSUE TITLE
Common way to trace function entry/exit

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/logging#15]
In a few places in the DUNE-DAQ codebase, we have trace calls for function entry and exit. Eg:

https://github.com/DUNE-DAQ/readout/blob/cd9203c38cb3e6a5165fb91f45a6709f4920ee72/plugins/DataLinkHandler.cpp#L43

https://github.com/DUNE-DAQ/trigger/blob/c5e20db37b81889f825ce49940e40fed471bdaaf/plugins/TriggerPrimitiveMaker.cpp#L101

It might be worth finding a way to wrap up this pattern in some common code that modules could use. I think the advantages would be:

* reduced code in functions that's unrelated to the "business logic"
* guaranteed common output format and log level of entry/exit messages
* guarantee that exit message is printed, even with multiple exit points (depending on implementation - see below)

One possibility for implementing this would be with a macro called at the start of each relevant function which creates an object whose ctor prints the entry message and whose dtor prints the exit message, as outlined here:

https://pileborg.se/2016/07/simple-function-call-tracing-in-c/

There might be other better ways to do it too

**Comment by brettviren** [comment]
I'd think this would be a job for the `DAQModuleManager` 

In fact it is partly implemented

https://github.com/DUNE-DAQ/appfwk/blob/develop/src/DAQModuleManager.cpp#L217

Fleshed out there, some "log map" may be appropriate.  This would map module instance name and command name to a log level and that would determine for which calls to `execute_command()` get dressed with log calls.  

I think the "log map" would best be specified in the `init` command object though perhaps it would be out-of-band of CCM and specified on the CLI?

**Comment by ron003** [comment]
There is a TLOG_ENTEX() streamer that is documented at the top of the trace.h file:
[https://github.com/art-daq/trace/blob/58433e1c560c4c6538c6f6fc79b04a106691749f/include/TRACE/trace.h#L60-L78](https://github.com/art-daq/trace/blob/58433e1c560c4c6538c6f6fc79b04a106691749f/include/TRACE/trace.h#L60-L78)
