### ISSUE TITLE
CMakeLists needs update/adjustment for new version of TRACE

### ISSUE THREAD

**Issue by ron003** [DUNE-DAQ/logging#17]
An issue was found with the v3.16.02 version of TRACE. There has been a v3.17.03 version used at fermi which fixes the issue. However, with the v3.17.03 version, just in the UPS environment, there is an issue with TRACEConfig.cmake file. This can be fixed in the logging CMakeLists.txt file. However, going forward -- a new version of TRACE i.e. v3.17.04 has a TRACEConfig.cmake which uses the more modern cmake TARGET method for dependencies -- this would also require an adjustment to the logging CMakeLists.txt file.

**Comment by dingp** [comment]
related PR #18 has been merged.
