### ISSUE TITLE
ers::fatal should exit the program

### ISSUE THREAD

**Issue by Juravenator** [DUNE-DAQ/logging#7]
Currently, `ers::fatal();` does not exit the program, contrary to conventional behavior of fatal.

Examples:
- PEP: https://www.python.org/dev/peps/pep-0282/#levels
- glog: http://rpg.ifi.uzh.ch/docs/glog.html
- log: https://golang.org/pkg/log/#Logger.Fatal

Current workaround:
```C++
auto issue = ...
ers::fatal(issue);
exit(EXIT_FAILURE);
```

**Comment by ron003** [comment]
John told me that Giovanna vetoed this issue, so I'll "Close with comment."
Another way to "workaround" is to add "exit" to the value of the DUNEDAQ_ERS_FATAL environment variable as such:
`DUNEDAQ_ERS_FATAL=erstrace,lstderr,exit`
